# Generated by Django 3.1.7 on 2021-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='my_feeling',
            field=models.CharField(choices=[(1, '좋음'), (2, '매우 좋음'), (3, '나쁨'), (4, '화남'), (5, '피곤함')], default=1, max_length=5),
        ),
    ]
